name: shop_layout
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-366.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_screenutil: ^5.7.0
  flutter_bloc: ^8.1.2
  path_provider: ^2.0.14
  collection: ^1.17.1
  http: ^0.13.6
  shimmer: ^2.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  easy_splash_screen: ^1.0.4
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/books.png
    - assets/images/filter.png
    - assets/images/gps.png
    - assets/images/pc.png
    - assets/images/profile.png
    - assets/images/pulsing_heart.png
    - assets/images/qr_code.png
    - assets/images/shop.png
    - assets/images/slider.png
    - assets/images/smartphone.png
    - assets/images/magnifier.png
    - assets/images/camera.png
    - assets/images/chip.png
    - assets/images/cpu.png
    - assets/images/external_card.png
    - assets/images/trash.png
    - assets/images/logo.png

  fonts:
    - family: Mark-Pro
      fonts:
        - asset: assets/fonts/Mark-Pro.ttf
